command_timeout = 10000

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
$fill\
$git_metrics\
$python\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[fill]
symbol = " "

[directory]
style = "fg:#212736 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"
format = '[+$added]($added_style)/[-$deleted ]($deleted_style)'

[python]
detect_folders = ["__pycache__", "venv"]
detect_files = ["__init__.py", "pytest.ini", "pyrightconfig.json"]
detect_extensions = ["py"]
style = "bg:#306998"
format = '[[[](bold fg:#306998) $virtualenv $version](fg:white bg:#306998)[ ](fg:#306998)]($style)'

# [python]
# detect_extensions = ["py"]
# style = "bg:#394260"
# format = '[[[](fg:#394260) $virtualenv $version](fg:#769ff0 bg:#394260)[ ](fg:#394260)]($style)'

[nodejs]
detect_folders = ["node_modules"]
detect_extensions = ["js", "ts", "jsx", "tsx"]
symbol = ""
style = "bg:#83BA63"
format = '[[[](bold fg:#83BA63)$symbol $version](fg:#212736 bg:#83BA63)[ ](bold fg:#83BA63)]($style)'

# [nodejs]
# symbol = ""
# style = "bg:#394260"
# format = '[[[](fg:#394260)$symbol $version](fg:#769ff0 bg:#394260)[ ](fg:#394260)]($style)'

[rust]
symbol = ""
style = "bg:#AF400E"
format = '[[[](fg:#AF400E)$symbol ($version) ](fg:#212736 bg:#AF400E)[ ](fg:#AF400E)]($style)'

# [rust]
# symbol = ""
# style = "bg:#394260"
# format = '[[[](fg:#394260)$symbol ($version) ](fg:#769ff0 bg:#394260)[ ](bold fg:#394260)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
disabled = false
success_symbol = "[>](bold green)"
error_symbol = "[×](bold red)"
vicmd_symbol = "[<](bold green)"
