require("plugins.lspconfig")
require("plugins.coq")
require("plugins.colorscheme")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.neocolumn")
-- require("plugins.dashboard")
require("plugins.barbecue")
-- require("plugins.feline")
require("plugins.lualine")
require("plugins.barbar")
require("plugins.nvim_comment")
require("plugins.nvim-autopairs")
require("plugins.formatter")
require("plugins.wilder")
-- require("plugins.oneterm")
require("plugins.toggleterm")
